### PR TITLE
Generate key pair on offline

### PR DESCRIPTION
**Pull request by ender503**
In the practical use case, user will generate the key pair and manage
it by itself, it is improper to generate it from the server-side API,
so we remove the 'keyPairs' API and generate the key pair on the
offline.

Since the 'keyPairs' API is removed, remove 'fetchKeyParis' action,
'keyPairs' reducer and constants as well.

### CODE REVIEW

**Comment by ender503** [comment]
The commit message is misleading, I'll update the commit message.
On this demo site, the user doesn't need to generate the key pair by itself.
The key pair will be generated by Javascript on the browser, instead of generated on the server-side.

**Comment by ender503** [comment]
The previous commit message is misleading.
The users don't need to generate the key pair on the "client-side".
This demo site will automate to generate key pair for them on the "browser-side".

**Comment by jserv** [comment]
"Browser-side" is misleading though. I think "offline" key generation would be accurate.

**Comment by jserv** [comment]
I defer to the opinion of @HexRabbit

**Pull request merged**
